# -*- coding:utf-8 -*-
# filename: units/locals.py
# by スノル

B_LENGTH = 0
B_MASS = 1
B_TIME = 2
B_CURRENT = 3
B_TEMPERATURE = 4
B_AMOUNT = 5
B_LUMINOUS = 6

B_FREQUENCY = 7
B_FORCE = 8
B_PRESSURE = 9
B_ENERGY = 10
B_POWER = 11
B_CHARGE = 12
B_VOLTAGE = 13
B_ELEC_CAPACITANCE = 14
B_ELEC_RESISTANCE = 15
B_ELEC_CONDUCTANCE = 16
B_MAGNETIC_FLUX = 17
B_MAGNETIC_FIELD_STRENGTH = 18
B_INDUCTANCE = 19
B_LUMINOUS_FLUX = 20
B_ILLUMINANCE = 21
B_RADIOACTIVITY = 22
B_ABSORBED_DOSE = 23
B_EQUIVALENT_DOSE = 24
B_CATALYTIC_ACTIVITY = 25

PRENAME = '_unit_'
